_wandb:
    value:
        cli_version: 0.23.0
        e:
            ep10ph031bvw4m0etgr9fcbmhjb3eu1e:
                codePath: c:\Users\adeli\Documents 4-Q1\Web Analytics\Final Project GitHub\web-analytics-project-repo\XGBoost Linkedin data.ipynb
                codePathLocal: XGBoost Linkedin data.ipynb
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "1023004372992"
                        used: "506843676672"
                email: 100496657@alumnos.uc3m.es
                executable: c:\Users\adeli\anaconda3\envs\dsnp1\python.exe
                git:
                    commit: 0b5bfa4a42b3a5e249007d54dafaa8d3ef0172a1
                    remote: https://github.com/enicaking/web-analytics-project-repo.git
                host: AdePortatil
                memory:
                    total: "16832106496"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\adeli\Documents 4-Q1\Web Analytics\Final Project GitHub\web-analytics-project-repo\XGBoost Linkedin data.ipynb
                python: CPython 3.12.11
                root: C:\Users\adeli\Documents 4-Q1\Web Analytics\Final Project GitHub\web-analytics-project-repo
                startedAt: "2025-11-29T19:26:37.555273Z"
                writerId: ep10ph031bvw4m0etgr9fcbmhjb3eu1e
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 53
            "3":
                - 2
                - 14
            "4": 3.12.11
            "5": 0.23.0
            "8":
                - 1
                - 3
            "12": 0.23.0
            "13": windows-amd64
colsample_bytree:
    value: 0.8
early_stopping_rounds:
    value: 40
gamma:
    value: 0
learning_rate:
    value: 0.05
max_depth:
    value: 6
min_child_weight:
    value: 1
num_boost_round:
    value: 800
reg_alpha:
    value: 0.5
reg_lambda:
    value: 3
subsample:
    value: 0.8
